/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.asksunny.rpc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RpcType implements org.apache.thrift.TEnum {
  SYNC(1),
  ASYNC_POLL(2),
  ASYNC_DELAY(3),
  ASYNC_CALLBACK(4);

  private final int value;

  private RpcType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RpcType findByValue(int value) { 
    switch (value) {
      case 1:
        return SYNC;
      case 2:
        return ASYNC_POLL;
      case 3:
        return ASYNC_DELAY;
      case 4:
        return ASYNC_CALLBACK;
      default:
        return null;
    }
  }
}
